### ISSUE TITLE
Possible to include file .wasm extension? 

### ISSUE THREAD

**Issue by thyeun** [Alhadis/language-webassembly#1]
Possible to include file .wasm extension, because current version of webassembly will generate .wasm extension too

**Comment by Alhadis** [comment]
Yes, but `.wasm` files are binary, not text. WebAssembly has two forms:

* `.wasm` is a binary format that's read and generated by machines
* `.wast` is a text format that's readable and editable by humans

Because `.wasm` files aren't supposed to edited by hand, it makes no sense for them be highlighted like ordinary code.

**Comment by thyeun** [comment]
i understand that, to be appear something like the below, 

![screenshot_2018-07-14_21-26-42](https://user-images.githubusercontent.com/1939446/42724872-fa2a67d2-87ac-11e8-9938-bb663cce4c03.png)

**Comment by Alhadis** [comment]
Hang on. That `index.wasm` file should be named `index.wast`. Unless it's being decompiled by the editor when you open it...

How is that file stored on disk? Run the following command and tell me what it outputs:
~~~bash
file index.wasm
~~~

If you have a package that dynamically disassembles `.wasm` files when you open them, then yes, we should definitely add it to the supported extensions list...

**Comment by thyeun** [comment]
Not sure what you looking at, but below is the output pic.

![screenshot_2018-07-14_21-53-27](https://user-images.githubusercontent.com/1939446/42725073-8f56c82a-87b0-11e8-8a1d-e10a8c40dc20.png)

**Comment by Alhadis** [comment]
Oh, you're using Windows? Alright, what do you see when you open `index.wasm` in  `Notepad.exe`?

**Comment by thyeun** [comment]
Not using windows, that one is i3wm

**Comment by Alhadis** [comment]
I'm not sure what implementation of [`file(1)`](https://linux.die.net/man/1/file) you have, but this is the first I've seen that outputs timestamps instead of `"ASCII text"` or `data`.

I'm basically asking, is that file being stored on disk in **binary** format, or is **text**? If it's **text**, then the filename is incorrect and the extension should be `.wast` instead.

Note that Atom also allows you to customise [filetype associations](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition) using `~/.atom/config.cson`.

**Comment by thyeun** [comment]
this is what i see on ATOM ```index.wasm```

![screenshot_2018-07-14_22-06-16](https://user-images.githubusercontent.com/1939446/42725192-42894674-87b2-11e8-8f26-0fc784de69e2.png)

**Comment by thyeun** [comment]
the first pic that view ```index.wasm``` not in binary are using ```VS code```, and the extension manage to change binary into readable content. 

yes, that file are binary format, just ```VS code``` having an extension that manage to make it viewable/readable.

And that why i'm asking possible to make it readable.

**Comment by Alhadis** [comment]
Are you using this package in VS Code, then? I wasn't aware that was possible.

Guess I'll just add the extension then, since on-the-fly disassembly isn't something I considered when deciding the file extensions list...

**Comment by thyeun** [comment]
in ```VS code``` need to install an extension only than it is possible to be viewable/readable. and as you can see from the pic below, the right bottom corner ```index.wasm``` the file extension are return with ```webassembly```  (in VS code) but from ATOM the file extension still return as ```plain text```

![screenshot_2018-07-14_22-17-48](https://user-images.githubusercontent.com/1939446/42725295-19eeb292-87b4-11e8-85f3-e4fe28720281.png)

**Comment by Alhadis** [comment]
I'm so confused... Are you asking for this package to provide on-the-fly disassembly of `.wasm` files when opened in Atom? Or do you simply want syntax highlighting whenever you open any sort of `.wasm` file?

**Comment by thyeun** [comment]
=.= sorry for confusing you, just need the index.wasm to be readable in ATOM.

change this 

![screenshot_2018-07-14_22-06-16](https://user-images.githubusercontent.com/1939446/42725484-bca0cf1e-87b6-11e8-872a-d4d5102db8ab.png)

to this 

![screenshot_2018-07-14_22-17-48](https://user-images.githubusercontent.com/1939446/42725486-cb08746c-87b6-11e8-8ac3-aafc1a89a839.png)

**Comment by Alhadis** [comment]
Right, I get you now. You want a feature to dynamically disassemble `.wasm` files when the user opens them, and reassmbles them when they're changed.

I'll consider it, but it's a big ask. My access to Atom is also limited these days, which may impact my ability to implement the feature you're asking...

**Comment by thyeun** [comment]
thanks and sorry for disturbing your real life work.

i need it because my team-mate here some of them are not consider using VS code (many anti-windows product) that why i have to using ATOM for tally up all the working tool.

sorry for trouble you.
